apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco-pichincha-deployment
  labels:
    app: banco-pichincha
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: banco-pichincha
      
  template:
    metadata:
      labels:
        app: banco-pichincha
        tier: banco-pichincha
    spec:
      containers:
        - name: banco-pichincha
          image: gcr.io/industrial-gist-378420/banco-pichincha:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            name: banco-pichincha


---
apiVersion: v1
kind: Service
metadata:
  name: banco-pichincha-service
  labels:
    app: banco-pichincha
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: banco-pichincha
    tier: banco-pichincha
  type: LoadBalancer